# Generated by Django 2.1 on 2018-10-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
