# Generated by Django 2.1 on 2018-10-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0002_auto_20181021_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
