# Generated by Django 2.1 on 2018-10-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0003_auto_20181021_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('pamount', models.FloatField(blank=True, null=True)),
                ('iamount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paid',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transact.Paid'),
        ),
    ]
