# Generated by Django 2.1 on 2018-10-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0004_auto_20181022_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='transact.Paid'),
        ),
    ]
