# Generated by Django 2.1 on 2018-10-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0005_auto_20181022_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='transact.Borrower'),
        ),
    ]
